//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Sinh_Vien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public int Maphong { get; set; }
        public string Toanha { get; set; }
        public Nullable<int> Sodien { get; set; }
        public Nullable<int> Sonuoc { get; set; }
        public string Loaiphong { get; set; }
    }
}
