//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Sinh_Vien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyKTXSVEntitiesFinal1 : DbContext
    {
        public QuanLyKTXSVEntitiesFinal1()
            : base("name=QuanLyKTXSVEntitiesFinal1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Loaiphong> Loaiphongs { get; set; }
        public virtual DbSet<Phieudathutien> Phieudathutiens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<Sinhvien> Sinhviens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Taikhoan> Taikhoans { get; set; }
        public virtual DbSet<Thanhpho> Thanhphoes { get; set; }
        public virtual DbSet<Truong> Truongs { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int ups_CapnhatLP(string maLP, string tenLP, Nullable<decimal> tiendien, Nullable<decimal> tiennuoc)
        {
            var maLPParameter = maLP != null ?
                new ObjectParameter("MaLP", maLP) :
                new ObjectParameter("MaLP", typeof(string));
    
            var tenLPParameter = tenLP != null ?
                new ObjectParameter("TenLP", tenLP) :
                new ObjectParameter("TenLP", typeof(string));
    
            var tiendienParameter = tiendien.HasValue ?
                new ObjectParameter("Tiendien", tiendien) :
                new ObjectParameter("Tiendien", typeof(decimal));
    
            var tiennuocParameter = tiennuoc.HasValue ?
                new ObjectParameter("Tiennuoc", tiennuoc) :
                new ObjectParameter("Tiennuoc", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_CapnhatLP", maLPParameter, tenLPParameter, tiendienParameter, tiennuocParameter);
        }
    
        public virtual int ups_CapnhatPhong(Nullable<int> maphong, string toanha, Nullable<int> sodien, Nullable<int> sonuoc, string loaiphong)
        {
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            var toanhaParameter = toanha != null ?
                new ObjectParameter("Toanha", toanha) :
                new ObjectParameter("Toanha", typeof(string));
    
            var sodienParameter = sodien.HasValue ?
                new ObjectParameter("Sodien", sodien) :
                new ObjectParameter("Sodien", typeof(int));
    
            var sonuocParameter = sonuoc.HasValue ?
                new ObjectParameter("Sonuoc", sonuoc) :
                new ObjectParameter("Sonuoc", typeof(int));
    
            var loaiphongParameter = loaiphong != null ?
                new ObjectParameter("Loaiphong", loaiphong) :
                new ObjectParameter("Loaiphong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_CapnhatPhong", maphongParameter, toanhaParameter, sodienParameter, sonuocParameter, loaiphongParameter);
        }
    
        public virtual int ups_CapnhatSV(Nullable<int> mSSV, string hoten, string gioitinh, string truonghoc, Nullable<System.DateTime> ngaysinh, string soDT, Nullable<int> noisinh, Nullable<int> maphong)
        {
            var mSSVParameter = mSSV.HasValue ?
                new ObjectParameter("MSSV", mSSV) :
                new ObjectParameter("MSSV", typeof(int));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("Gioitinh", gioitinh) :
                new ObjectParameter("Gioitinh", typeof(string));
    
            var truonghocParameter = truonghoc != null ?
                new ObjectParameter("Truonghoc", truonghoc) :
                new ObjectParameter("Truonghoc", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("Ngaysinh", ngaysinh) :
                new ObjectParameter("Ngaysinh", typeof(System.DateTime));
    
            var soDTParameter = soDT != null ?
                new ObjectParameter("SoDT", soDT) :
                new ObjectParameter("SoDT", typeof(string));
    
            var noisinhParameter = noisinh.HasValue ?
                new ObjectParameter("Noisinh", noisinh) :
                new ObjectParameter("Noisinh", typeof(int));
    
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_CapnhatSV", mSSVParameter, hotenParameter, gioitinhParameter, truonghocParameter, ngaysinhParameter, soDTParameter, noisinhParameter, maphongParameter);
        }
    
        public virtual int ups_CapnhatTK(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_CapnhatTK", usernameParameter, passwordParameter);
        }
    
        public virtual int ups_CapnhatTP(Nullable<int> maTP, string tenTP)
        {
            var maTPParameter = maTP.HasValue ?
                new ObjectParameter("MaTP", maTP) :
                new ObjectParameter("MaTP", typeof(int));
    
            var tenTPParameter = tenTP != null ?
                new ObjectParameter("TenTP", tenTP) :
                new ObjectParameter("TenTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_CapnhatTP", maTPParameter, tenTPParameter);
        }
    
        public virtual int ups_CapnhatTruong(string matruong, string tentruong)
        {
            var matruongParameter = matruong != null ?
                new ObjectParameter("Matruong", matruong) :
                new ObjectParameter("Matruong", typeof(string));
    
            var tentruongParameter = tentruong != null ?
                new ObjectParameter("Tentruong", tentruong) :
                new ObjectParameter("Tentruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_CapnhatTruong", matruongParameter, tentruongParameter);
        }
    
        public virtual int ups_XoaLP(string maLP)
        {
            var maLPParameter = maLP != null ?
                new ObjectParameter("MaLP", maLP) :
                new ObjectParameter("MaLP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_XoaLP", maLPParameter);
        }
    
        public virtual int ups_XoaPhieuthutien(Nullable<int> maphong)
        {
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_XoaPhieuthutien", maphongParameter);
        }
    
        public virtual int ups_XoaPhong(Nullable<int> maphong)
        {
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_XoaPhong", maphongParameter);
        }
    
        public virtual int ups_XoaSV(Nullable<int> mSSV)
        {
            var mSSVParameter = mSSV.HasValue ?
                new ObjectParameter("MSSV", mSSV) :
                new ObjectParameter("MSSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_XoaSV", mSSVParameter);
        }
    
        public virtual int ups_XoaTK(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_XoaTK", usernameParameter);
        }
    
        public virtual int ups_XoaTP(Nullable<int> maTP)
        {
            var maTPParameter = maTP.HasValue ?
                new ObjectParameter("MaTP", maTP) :
                new ObjectParameter("MaTP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_XoaTP", maTPParameter);
        }
    
        public virtual int ups_XoaTruong(string matruong)
        {
            var matruongParameter = matruong != null ?
                new ObjectParameter("Matruong", matruong) :
                new ObjectParameter("Matruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ups_XoaTruong", matruongParameter);
        }
    
        public virtual ObjectResult<usp_Danhsachphong_Result> usp_Danhsachphong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Danhsachphong_Result>("usp_Danhsachphong");
        }
    
        public virtual ObjectResult<usp_DanhsachSV_Result> usp_DanhsachSV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DanhsachSV_Result>("usp_DanhsachSV");
        }
    
        public virtual ObjectResult<Nullable<int>> usp_DemSLSVtrongPhong(Nullable<int> maphong)
        {
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_DemSLSVtrongPhong", maphongParameter);
        }
    
        public virtual ObjectResult<usp_DS_Taikhoan_Result> usp_DS_Taikhoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DS_Taikhoan_Result>("usp_DS_Taikhoan");
        }
    
        public virtual ObjectResult<usp_DSPhong_Result> usp_DSPhong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DSPhong_Result>("usp_DSPhong");
        }
    
        public virtual ObjectResult<usp_KTDN_TK_Result> usp_KTDN_TK(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_KTDN_TK_Result>("usp_KTDN_TK", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<usp_LocDSSVtheoMSSV_Result> usp_LocDSSVtheoMSSV(Nullable<int> mSSV)
        {
            var mSSVParameter = mSSV.HasValue ?
                new ObjectParameter("MSSV", mSSV) :
                new ObjectParameter("MSSV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_LocDSSVtheoMSSV_Result>("usp_LocDSSVtheoMSSV", mSSVParameter);
        }
    
        public virtual ObjectResult<usp_LocSVtheoPhong_Result> usp_LocSVtheoPhong(Nullable<int> maphong)
        {
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_LocSVtheoPhong_Result>("usp_LocSVtheoPhong", maphongParameter);
        }
    
        public virtual int usp_ThemLP(string maLP, string tenLP, Nullable<decimal> tiendien, Nullable<decimal> tiennuoc)
        {
            var maLPParameter = maLP != null ?
                new ObjectParameter("MaLP", maLP) :
                new ObjectParameter("MaLP", typeof(string));
    
            var tenLPParameter = tenLP != null ?
                new ObjectParameter("TenLP", tenLP) :
                new ObjectParameter("TenLP", typeof(string));
    
            var tiendienParameter = tiendien.HasValue ?
                new ObjectParameter("Tiendien", tiendien) :
                new ObjectParameter("Tiendien", typeof(decimal));
    
            var tiennuocParameter = tiennuoc.HasValue ?
                new ObjectParameter("Tiennuoc", tiennuoc) :
                new ObjectParameter("Tiennuoc", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemLP", maLPParameter, tenLPParameter, tiendienParameter, tiennuocParameter);
        }
    
        public virtual int usp_Themphieudathu(Nullable<int> sonuoc, Nullable<int> tongtiennuoc, Nullable<int> sodien, Nullable<int> tongtiendien, Nullable<int> tongtien, Nullable<int> maphong)
        {
            var sonuocParameter = sonuoc.HasValue ?
                new ObjectParameter("Sonuoc", sonuoc) :
                new ObjectParameter("Sonuoc", typeof(int));
    
            var tongtiennuocParameter = tongtiennuoc.HasValue ?
                new ObjectParameter("Tongtiennuoc", tongtiennuoc) :
                new ObjectParameter("Tongtiennuoc", typeof(int));
    
            var sodienParameter = sodien.HasValue ?
                new ObjectParameter("Sodien", sodien) :
                new ObjectParameter("Sodien", typeof(int));
    
            var tongtiendienParameter = tongtiendien.HasValue ?
                new ObjectParameter("Tongtiendien", tongtiendien) :
                new ObjectParameter("Tongtiendien", typeof(int));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("Tongtien", tongtien) :
                new ObjectParameter("Tongtien", typeof(int));
    
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Themphieudathu", sonuocParameter, tongtiennuocParameter, sodienParameter, tongtiendienParameter, tongtienParameter, maphongParameter);
        }
    
        public virtual int usp_ThemSV(Nullable<int> mSSV, string hoten, string gioitinh, string truonghoc, Nullable<System.DateTime> ngaysinh, string soDT, Nullable<int> noisinh, Nullable<int> maphong)
        {
            var mSSVParameter = mSSV.HasValue ?
                new ObjectParameter("MSSV", mSSV) :
                new ObjectParameter("MSSV", typeof(int));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("Gioitinh", gioitinh) :
                new ObjectParameter("Gioitinh", typeof(string));
    
            var truonghocParameter = truonghoc != null ?
                new ObjectParameter("Truonghoc", truonghoc) :
                new ObjectParameter("Truonghoc", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("Ngaysinh", ngaysinh) :
                new ObjectParameter("Ngaysinh", typeof(System.DateTime));
    
            var soDTParameter = soDT != null ?
                new ObjectParameter("SoDT", soDT) :
                new ObjectParameter("SoDT", typeof(string));
    
            var noisinhParameter = noisinh.HasValue ?
                new ObjectParameter("Noisinh", noisinh) :
                new ObjectParameter("Noisinh", typeof(int));
    
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemSV", mSSVParameter, hotenParameter, gioitinhParameter, truonghocParameter, ngaysinhParameter, soDTParameter, noisinhParameter, maphongParameter);
        }
    
        public virtual int usp_ThemTK(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemTK", usernameParameter, passwordParameter);
        }
    
        public virtual int usp_ThemTP(Nullable<int> maTP, string tenTP)
        {
            var maTPParameter = maTP.HasValue ?
                new ObjectParameter("MaTP", maTP) :
                new ObjectParameter("MaTP", typeof(int));
    
            var tenTPParameter = tenTP != null ?
                new ObjectParameter("TenTP", tenTP) :
                new ObjectParameter("TenTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemTP", maTPParameter, tenTPParameter);
        }
    
        public virtual int usp_ThemTruong(string matruong, string tentruong)
        {
            var matruongParameter = matruong != null ?
                new ObjectParameter("Matruong", matruong) :
                new ObjectParameter("Matruong", typeof(string));
    
            var tentruongParameter = tentruong != null ?
                new ObjectParameter("Tentruong", tentruong) :
                new ObjectParameter("Tentruong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ThemTruong", matruongParameter, tentruongParameter);
        }
    
        public virtual int usp_TheuPhong(Nullable<int> maphong, string toanha, Nullable<int> sodien, Nullable<int> sonuoc, string loaiphong)
        {
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            var toanhaParameter = toanha != null ?
                new ObjectParameter("Toanha", toanha) :
                new ObjectParameter("Toanha", typeof(string));
    
            var sodienParameter = sodien.HasValue ?
                new ObjectParameter("Sodien", sodien) :
                new ObjectParameter("Sodien", typeof(int));
    
            var sonuocParameter = sonuoc.HasValue ?
                new ObjectParameter("Sonuoc", sonuoc) :
                new ObjectParameter("Sonuoc", typeof(int));
    
            var loaiphongParameter = loaiphong != null ?
                new ObjectParameter("Loaiphong", loaiphong) :
                new ObjectParameter("Loaiphong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_TheuPhong", maphongParameter, toanhaParameter, sodienParameter, sonuocParameter, loaiphongParameter);
        }
    
        public virtual ObjectResult<usp_Thongkediennuoc_Result> usp_Thongkediennuoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Thongkediennuoc_Result>("usp_Thongkediennuoc");
        }
    
        public virtual ObjectResult<usp_Tiendiennuoc_Result> usp_Tiendiennuoc(Nullable<int> maphong)
        {
            var maphongParameter = maphong.HasValue ?
                new ObjectParameter("Maphong", maphong) :
                new ObjectParameter("Maphong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Tiendiennuoc_Result>("usp_Tiendiennuoc", maphongParameter);
        }
    }
}
