//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Sinh_Vien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinhvien
    {
        public int MSSV { get; set; }
        public string Hoten { get; set; }
        public string Gioitinh { get; set; }
        public string Truonghoc { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string SoDT { get; set; }
        public Nullable<int> Noisinh { get; set; }
        public int Maphong { get; set; }
    }
}
