//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Sinh_Vien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truong
    {
        public string Matruong { get; set; }
        public string Tentruong { get; set; }
    }
}
